# -*- encoding: utf-8 -*-

{
	'name': 'Seguimiento de trabajo de grado',
	'version': '1.0',
	'category': 'education',
	'sequence': 100,
	'summary': 'Proceso trabajo de grado online a distancia',
	'description': 'Desarrolla tu proceso de trabajo de grado de forma no prensencial, sacando el mayor provecha a las tecnologias de la informacion.',
	'website': 'https://www.ues.edu.sv',
	'depends': [
	    'web',
        'web_kanban',
		'decimal_precision',
		'hr',
		'hr_recruitment',
		'project',
		'calendar',
		'fetchmail',
		'web_kanban_gauge',
		'utm',
		'document',
		'web_tour',
		'report',
	],
	'data': [
    	'security/topic_grade_security.xml',
		'security/ir.model.access.csv',
		'views/topic_grade_online_views.xml',
		'views/topic_grade_online_templates.xml',
		'views/topic_grade_online_topic_views.xml',
		'report/report_evaluations_1.xml',
		'report/report_topic_grade.xml',
		'report/report_reference.xml',
		'report/template.xml',
	],
	'installable': True,
	'auto_install': False,
	'application': True,
}